#!/bin/bash
if [[ "$1" != http* ]]; then
	echo "Errore URL"; exit 1
fi

if [[ "$1" == */ ]]; then
	mkdir "$2"_w || exit 1
	cd "$2"_w || exit 1
	downloader "$1" || exit 1
	joiner "$2" || exit 1
	mv -f "$2" ..
	rm -rf ../"$2"_w
elif [[ "$1" == *.mp4 ]]; then
	wget -q --show-progress "$1" -O "$2" || exit 1
else
	echo "URL non supportata"; exit 1
fi
