#!/bin/bash
# Scarico due flussi video e audio e poi li unisco
if test -f "$3"; then
    echo "    '$3' file gia' scaricato"
	exit 1
fi

echo "    Downloading '$3'"

#-- Creo la cartella di lavoro e poi mi sposto dentro
mkdir -p "$3"_w
cd "$3"_w || exit 1

#-- Scarico il flusso audio (webcam)
pdown "$1" webcam.mp4 || exit 1

#-- Scarico il flusso video (schermo)
pdown "$2" screen.mp4 || exit 1

echo "Unisco webcam.mp4 & screen.mp4 di '$3'"
ffmpeg -hwaccel auto -hide_banner -loglevel warning -i screen.mp4 -i webcam.mp4 -c copy "$3" || exit 1

#-- Sposto il file ottentuto fuori e cancello la cartella di lavoro
mv -f "$3" ..
rm -rf ../"$3"_w
