#!/bin/bash
if [[ "$1" == */ ]]; then # se termina per / e' un flusso .ts
    echo "Downloading '$2'"
    #-- Creo la cartella di lavoro e poi mi sposto dentro
	mkdir -p "$2"_w
	cd "$2"_w || exit 1
	
	#-- Scarico tutti .ts e poi li unisco
	downloader "$1" || exit 1
	joiner "$2" || exit 1

	#-- Sposto il file ottentuto fuori e cancello la cartella di lavoro
	mv -f "$2" ..
	rm -rf ../"$2"_w
	exit
fi

# se e' un file .mp4 posso scaricarlo con wget
wget -q --show-progress "$1" -O "$2" || exit 1
